---
#By Default this service will pick ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: temp-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80